#!/bin/bash

cd /opt/mdvr/
python3 -m venv venv
/opt/mdvr/venv/bin/pip install -r requirements.txt

systemctl stop mdvr_rs.service
systemctl disable mdvr_rs.service

systemctl enable mdvr_space_check.timer
systemctl enable mdvr.service
systemctl enable mdvr_web.service
systemctl enable mdvr_upload.timer
systemctl enable mdvr_system_guard.timer
systemctl enable mdvr_vpn_check.timer

rm /etc/nginx/sites-enabled/default
systemctl restart nginx

# Apply new venv
systemctl daemon-reload
systemctl restart mdvr.service
systemctl restart mdvr_upload.timer
systemctl restart mdvr_web.service
systemctl restart mdvr_space_check.timer
systemctl restart mdvr_system_guard.timer
systemctl restart mdvr_vpn_check.timer

timedatectl set-timezone "Europe/Kyiv"

systemctl daemon-reload

systemctl restart NetworkManager
