#!/bin/bash

cd /opt/mdvr/

# Ensure Python 3.11 installer runs once
systemctl enable --now python311_install.service || true

systemctl stop mdvr_rs.service
systemctl stop mdvr_rs.timer
systemctl disable mdvr_rs.service
systemctl disable mdvr_rs.timer

systemctl enable mdvr_space_check.timer
systemctl enable mdvr.timer
systemctl enable init_start.service
systemctl enable mdvr_web.timer
systemctl enable mdvr_upload.timer
systemctl enable mdvr_system_guard.timer
systemctl enable mdvr_vpn_check.timer

rm /etc/nginx/sites-enabled/default
systemctl restart nginx

# Apply new venv
systemctl daemon-reload
systemctl restart mdvr.timer
systemctl restart mdvr_upload.timer
systemctl restart init_start.service
systemctl restart mdvr_web.timer
systemctl restart mdvr_space_check.timer
systemctl restart mdvr_system_guard.timer
systemctl restart mdvr_vpn_check.timer

timedatectl set-timezone "Europe/Kyiv"

systemctl daemon-reload

systemctl restart NetworkManager
